In [1]:
#Credit Risk Resampling Techniques

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter

In [4]:
#Read the CSV and Perform Basic Data Cleaning

In [5]:
# Load the data
file_path = Path('lending_data.csv')
df = pd.read_csv(file_path)
df.head()

loan_size  interest_rate homeowner  borrower_income  debt_to_income  \
0    10700.0          7.672       own            52800        0.431818   
1     8400.0          6.692       own            43600        0.311927   
2     9000.0          6.963      rent            46100        0.349241   
3    10700.0          7.664       own            52700        0.430740   
4    10800.0          7.698  mortgage            53000        0.433962   

   num_of_accounts  derogatory_marks  total_debt loan_status  
0                5                 1       22800    low_risk  
1                3                 0       13600    low_risk  
2                3                 0       16100    low_risk  
3                5                 1       22700    low_risk  
4                5                 1       23000    low_risk

In [6]:
# Split the Data into Training and Testing

In [7]:
# Create our features
x_cols = [i for i in df.columns if i not in ("homeowner","loan_status")]
X = df[x_cols]

# Create our target
y = df["loan_status"]

In [8]:
X.describe()

loan_size  interest_rate  borrower_income  debt_to_income  \
count  77536.000000   77536.000000     77536.000000    77536.000000   
mean    9805.562577       7.292333     49221.949804        0.377318   
std     2093.223153       0.889495      8371.635077        0.081519   
min     5000.000000       5.250000     30000.000000        0.000000   
25%     8700.000000       6.825000     44800.000000        0.330357   
50%     9500.000000       7.172000     48100.000000        0.376299   
75%    10400.000000       7.528000     51400.000000        0.416342   
max    23800.000000      13.235000    105200.000000        0.714829   

       num_of_accounts  derogatory_marks    total_debt  
count     77536.000000      77536.000000  77536.000000  
mean          3.826610          0.392308  19221.949804  
std           1.904426          0.582086   8371.635077  
min           0.000000          0.000000      0.000000  
25%           3.000000          0.000000  14800.000000  
50%           4.000000          0.000000  18100.000000  
75%           4.000000          1.000000  21400.000000  
max          16.000000          3.000000  75200.000000

In [9]:
# Check the balance of our target values
y.value_counts()

low_risk     75036
high_risk     2500
Name: loan_status, dtype: int64

In [10]:
# Create X_train, X_test, y_train, y_test
# YOUR CODE HERE

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [13]:
#Simple Logistic Regression

In [14]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_train, y_train)

LogisticRegression(random_state=1)

In [15]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
y_pred = model.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.9520479254722232

In [16]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[  563,    56],
       [  102, 18663]], dtype=int64)

In [19]:
y_test

60914    low_risk
36843    low_risk
1966     low_risk
70137    low_risk
27237    low_risk
           ...   
45639    low_risk
11301    low_risk
51614    low_risk
4598     low_risk
2793     low_risk
Name: loan_status, Length: 19384, dtype: object

In [21]:
 # Print the imbalanced classification report
from imblearn.metrics import classification_report_imbalanced
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.85      0.91      0.99      0.88      0.95      0.90       619
   low_risk       1.00      0.99      0.91      1.00      0.95      0.91     18765

avg / total       0.99      0.99      0.91      0.99      0.95      0.91     19384



In [18]:
# Oversampling

In [19]:
# Naive Random Oversampling

In [20]:
# Resample the training data with the RandomOversampler
# YOUR CODE HERE

In [22]:
from imblearn.over_sampling import RandomOverSampler

In [23]:
ros = RandomOverSampler(random_state=1)
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)
Counter(y_resampled)

Counter({'low_risk': 56271, 'high_risk': 56271})

In [24]:
# Train the Logistic Regression model using the resampled data
# YOUR CODE HERE

In [25]:
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

LogisticRegression(random_state=1)

In [26]:
# Calculated the balanced accuracy score


In [27]:
balanced_accuracy_score(y_test, y_pred)

0.9520479254722232

In [28]:
# Display the confusion matrix
# YOUR CODE HERE

In [29]:
y_pred = model.predict(X_test)
confusion_matrix(y_test, y_pred)

array([[  615,     4],
       [  116, 18649]], dtype=int64)

In [29]:
# Print the imbalanced classification report
# YOUR CODE HERE

In [30]:
#report = sclassification_report_imbalanced(y_test, y_pred)
#print(report) 


classification_report_imbalanced(y_test, y_pred)

In [32]:
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.84      0.99      0.99      0.91      0.99      0.99       619
   low_risk       1.00      0.99      0.99      1.00      0.99      0.99     18765

avg / total       0.99      0.99      0.99      0.99      0.99      0.99     19384



In [32]:
#SMOTE Oversampling

In [33]:
# Resample the training data with SMOTE
from imblearn.over_sampling import SMOTE

In [34]:
X_resampled, y_resampled = SMOTE(random_state=1, sampling_strategy=1.0).fit_resample(X_train, y_train)

In [35]:
Counter(y_resampled)

Counter({'low_risk': 56271, 'high_risk': 56271})

In [36]:
# Train the Logistic Regression model using the resampled data
# YOUR CODE HERE

In [37]:
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

LogisticRegression(random_state=1)

In [38]:
# Calculated the balanced accuracy score
# YOUR CODE HERE

In [39]:
y_pred = model.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.9936781215845847

In [40]:
# Display the confusion matrix

confusion_matrix(y_test, y_pred)

array([[  615,     4],
       [  116, 18649]], dtype=int64)

In [42]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.84      0.99      0.99      0.91      0.99      0.99       619
   low_risk       1.00      0.99      0.99      1.00      0.99      0.99     18765

avg / total       0.99      0.99      0.99      0.99      0.99      0.99     19384



In [43]:
#print(classification_report_imbalanced(y_test, y_pred)) keeps erroring out as not callable thats why I cant make it look nicer

In [44]:
#Undersampling

In [45]:
# Resample the data using the ClusterCentroids resampler
# YOUR CODE HERE

In [46]:
from imblearn.under_sampling import ClusterCentroids

In [47]:
cc = ClusterCentroids(random_state=1)
X_resampled, y_resampled = cc.fit_resample(X_train, y_train)
Counter(y_resampled)

Counter({'high_risk': 1881, 'low_risk': 1881})

In [48]:
# Train the Logistic Regression model using the resampled data
# YOUR CODE HERE

In [49]:
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

LogisticRegression(random_state=1)

In [50]:
# Calculated the balanced accuracy score
# YOUR CODE HERE

In [51]:
balanced_accuracy_score(y_test, y_pred)

0.9936781215845847

In [52]:
# Display the confusion matrix
# YOUR CODE HERE

In [53]:
y_pred = model.predict(X_test)
confusion_matrix(y_test, y_pred)

array([[  608,    11],
       [  113, 18652]], dtype=int64)

In [54]:
# Print the imbalanced classification report
# YOUR CODE HERE

In [71]:
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.84      0.98      0.99      0.91      0.99      0.98       619
   low_risk       1.00      0.99      0.98      1.00      0.99      0.98     18765

avg / total       0.99      0.99      0.98      0.99      0.99      0.98     19384



In [56]:
#again if i use it in the print function it just errors out 

In [57]:
#Combination (Over and Under) Sampling 

In [58]:
# Resample the training data with SMOTEENN
# YOUR CODE HERE

In [69]:
from imblearn.combine import SMOTEENN

In [70]:
sm = SMOTEENN(random_state=1)
X_resampled, y_resampled = sm.fit_resample(X_train, y_train)
Counter(y_resampled)

Counter({'high_risk': 55382, 'low_risk': 55945})

In [61]:
# Train the Logistic Regression model using the resampled data
# YOUR CODE HERE

In [62]:
modelsmote = LogisticRegression(solver='lbfgs', random_state=1)
modelsmote.fit(X_resampled, y_resampled)

LogisticRegression(random_state=1)

In [63]:
# Calculated the balanced accuracy score
# YOUR CODE HERE

In [64]:
balanced_accuracy_score(y_test, y_pred)

0.9881037765371978

In [65]:
# Display the confusion matrix
# YOUR CODE HERE

In [66]:
y_pred = model.predict(X_test)
confusion_matrix(y_test, y_pred)

array([[  608,    11],
       [  113, 18652]], dtype=int64)

In [68]:
# Print the imbalanced classification report
# YOUR CODE HERE
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.84      0.98      0.99      0.91      0.99      0.98       619
   low_risk       1.00      0.99      0.98      1.00      0.99      0.98     18765

avg / total       0.99      0.99      0.98      0.99      0.99      0.98     19384

